name: pycomlink-dev
channels:
  - conda-forge
dependencies:
 - numpy
 - scipy
 - pandas<3
 - matplotlib
 - numba
 - h5py
 - xarray<2025.0.0
 - sparse
 - netcdf4
 - shapely
 - pyproj
 - tqdm
 - pykrige
 - scikit-learn
 - bottleneck
 - future
 - poligrain
 - pip
 - pip:
   - git+https://github.com/pycomlink/pycomlink.git#egg=pycomlink
